# playback controls
RIGHT           no-osd seek +5                  # seek 5 seconds forward
LEFT            no-osd seek -5                  # seek 5 seconds backward
Ctrl+RIGHT      frame-step                      # step forward one frame
Ctrl+LEFT       frame-back-step                 # step backward one frame
SPACE           cycle pause                     # toggle play/pause
HOME            seek 0 absolute                 # seek to the start
PGUP            add chapter -1                  # seek to the next chapter
PGDWN           add chapter +1                  # seek to the previous chapter

# volume controls
UP              add volume +5                   # increase volume by 5%
DOWN            add volume -5                   # decrease volume by 5%
WHEEL_UP        add volume +5                   # increase volume by 5% (mouse wheel)
WHEEL_DOWN      add volume -5                   # decrease volume by 5% (mouse wheel)
\               cycle mute                      # toggle mute

# audio controls
]               cycle audio                     # switch audio track
[               cycle audio down                # switch audio track backwards

# subtitle controls
'               cycle sub                       # switch subtitle track
;               cycle sub down                  # switch subtitle track backwards
,               add sub-delay -0.1              # decrease subtitle delay by 0.1 seconds
.               add sub-delay +0.1              # increase subtitle delay by 0.1 seconds
Ctrl+,          add sub-delay -1.0              # decrease subtitle delay by 1 second
Ctrl+.          add sub-delay +1.0              # increase subtitle delay by 1 second

# window controls
MBTN_LEFT_DBL   cycle fullscreen                # toggle fullscreen
Ctrl+ENTER      cycle fullscreen                # toggle fullscreen mode
ESC             set fullscreen no               # exit fullscreen mode

# MISC
s               screenshot video                # screenshot without subtitles
S               screenshot                      # screenshot with subtitles
I               script-binding display-stats-toggle                 # toggle display stats
Ctrl+h          cycle-values hwdec "no" "auto-safe" "auto-copy"     # toggle hardware decoding
