###########
# General #
###########

profile = high-quality

priority = high

vo = gpu-next
# gpu-context = d3d11
# gpu-api = d3d11
gpu-context = winvk
gpu-api = vulkan
hwdec = no

target-colorspace-hint = no

input-default-bindings = no


############
# Function #
############

idle = yes

save-position-on-quit = no

directory-mode = ignore

keep-open = yes
geometry = 1920x1080
keepaspect-window = yes
hidpi-window-scale = no

cache = yes
demuxer-max-bytes = 1024MiB
demuxer-max-back-bytes = 512MiB
icc-cache-dir = "~~/cache/icc"
gpu-shader-cache-dir = "~~/cache/shader"
watch-later-dir = "~~/cache/watch_later"


###########
#   OSD   #
###########

osd-bar = no


###########
#  Audio  #
###########

ao = wasapi

volume = 75
volume-max = 125
audio-channels = stereo

alang = jpn,ja,eng,en,chs,sc
audio-file-auto = fuzzy


###########
#  Video  #
###########

video-sync=display-resample

interpolation = yes
tscale = oversample
# cscale = catmull_rom

dither = fruit
deband = yes

icc-profile-auto = yes


##############
#  Subtitle  #
##############

sub-auto = fuzzy
sub-file-paths = sub;subtitles

slang = chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze
subs-fallback = yes

blend-subtitles = video


################
#  Screenshot  #
################

screenshot-format = png

screenshot-png-compression = 5
screenshot-png-filter = 0

screenshot-tag-colorspace = yes
screenshot-high-bit-depth = yes
screenshot-template = "~~desktop/%f_%wH-%wM-%wS.%wT_N%n"
